# ████████╗██╗  ██╗███████╗███╗   ███╗███████╗
# ╚══██╔══╝██║  ██║██╔════╝████╗ ████║██╔════╝
#    ██║   ███████║█████╗  ██╔████╔██║█████╗  
#    ██║   ██╔══██║██╔══╝  ██║╚██╔╝██║██╔══╝  
#    ██║   ██║  ██║███████╗██║ ╚═╝ ██║███████╗
#    ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝╚══════╝
# 

[flavor]
# dark = "catppuccin-mocha"
dark = "gruvbox-dark"
# dark = "kanagawa"


[plugin.full-border]
border_symbol = "│"
border_style  = { fg = "#FF5733" }
